---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/devqrone/autoscadereyta.com/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp htaccess $DEPLOYPATH
